version: "3.7"
services:
  uwsgi:
    build:
      context: .
      dockerfile: Dockerfile.uwsgi
    deploy:
      restart_policy:
        condition: on-failure
    env_file: ./.env
    image: andreburto/display
    networks:
      - nginx-proxy
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./display
        target: /display
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - uwsgi
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    networks:
      - nginx-proxy
    ports:
      - 80:80
networks:
  nginx-proxy: